#include "web_server.h"
#include "auxiliary/config_manager.h"
#include "auxiliary/vxinamespace.h"
#include <QTcpSocket>
#include <QWebSocket>

Q_LOGGING_CATEGORY(web_server, "WEB_SERVER:")

void WebServerManager::set_network(bool isstatic)
{
    QFile file("/etc/network/interfaces");
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        // WriteOnly -> Clear the original content
        QString restartCmd = "/etc/init.d/S40network restart";
        QTextStream out(&file);
        QString configContent;

        if(isstatic){
            configContent =
                "# interface file auto-generated by buildroot\n"
                "auto lo\n"
                "iface lo inet loopback\n\n"
                "auto eth0\n"
                "iface eth0 inet static\n"
                "    address " + ConfigManager::s_IP + "\n"
                "    netmask " + ConfigManager::s_SM + "\n"
                "    gateway " + ConfigManager::s_Gateway;

            out << configContent; file.close();
            if (system(restartCmd.toStdString().c_str()) == 0) {
                ConfigManager::getNetworkConfig();
                emit networkrefresh();
                return;
            }
        }else{
            configContent =
                "# interface file auto-generated by buildroot\n"
                "auto lo\n"
                "iface lo inet loopback\n\n"
                "auto eth0\n"
                "iface eth0 inet dhcp";

            out << configContent; file.close();
            if (system(restartCmd.toStdString().c_str()) == 0) {return;}
        }

        qCWarning(web_server) << "[refresh_interfaces]:/etc/init.d/S40network restart failed!";
        return;
    }

    qCWarning(web_server) << "[setinterfaces]:Cannot open interfaces file for writing";
    return;
}


void WebServerManager::sendHttpResponse(QTcpSocket *client, const QByteArray &content,const QString &contentType, int statusCode){
    QString statusText;
    switch (statusCode) {
        case 200: statusText = "OK"; break;
        case 204: statusText = "No Content"; break;
        case 400: statusText = "Bad Request"; break;
        case 404: statusText = "Not Found"; break;
        case 405: statusText = "Method Not Allowed"; break;
        case 500: statusText = "Internal Server Error"; break;
        default: statusText = "OK"; break;
    }

    QString header = QString(
        "HTTP/1.1 %1 %2\r\n"
        "Content-Type: %3; charset=utf-8\r\n"
        "Content-Length: %4\r\n"
        "Connection: close\r\n"
        "Access-Control-Allow-Origin: *\r\n"
        "\r\n"
    ).arg(QString::number(statusCode), statusText, contentType, QString::number(content.size()));

    client->write(header.toUtf8());
    client->write(content);
    //client->close(); // http1.0 long connection
}

const QHash<QString, QString> WebServerManager::m_staticFiles =
{
    {"/",                     ":/web/web/index.html"},
    {"/index.html",           ":/web/web/index.html"},
    {"/channels.html",        ":/web/web/channels.html"},
    {"/import.html",          ":/web/web/import.html"},
    {"/js/index.js",          ":/web/web/js/index.js"},
    {"/js/channels.js",       ":/web/web/js/channels.js"},
    {"/js/import.js",         ":/web/web/js/import.js"},
    {"/js/header.js",         ":/web/web/js/header.js"},
    {"/css/style.css",        ":/web/web/css/style.css"},
    {"/css/index.css",        ":/web/web/css/index.css"},
    {"/css/channels.css",     ":/web/web/css/channels.css"},
    {"/css/import.css",       ":/web/web/css/import.css"},
    {"/css/global.css",       ":/web/web/css/global.css"},
    {"/icon/leacesylogo.png", ":/web/web/icon/leacesylogo.png"},
    {"/icon/leacesyicon.png", ":/web/web/icon/leacesyicon.png"}
};

const QHash<QString, QString> WebServerManager::m_mimeTypes =
{
    {"html",                  "text/html"},
    {"css",                   "text/css"},
    {"js",                    "application/javascript"},
    {"json",                  "application/json"},
    {"png",                   "image/png"},
    {"jpg",                   "image/jpeg"},
    {"svg",                   "image/svg+xml"},
    {"ico",                   "image/x-icon"},
    {"txt",                   "text/plain"},
    {"xml",                   "application/xml"},
    {"pdf",                   "application/pdf"},
};

void WebServerManager::setupHTTPRoutes()
{
    m_apiRoutes["/api/device/info"] = [this](QTcpSocket* client) {
        QJsonObject response;
        response["model"] = ConfigManager::s_model;
        response["serial"] = ConfigManager::s_serialNumber;
        response["software"] = ConfigManager::s_firmwareVersion;
        response["hardware"] = ConfigManager::s_hardwareVersion;

        QByteArray jsonData = QJsonDocument(response).toJson();
        sendHttpResponse(client, jsonData, "application/json");
    };

    m_apiRoutes["/api/scpi_commands"] = [this](QTcpSocket* client) {
        QJsonObject response;
        QJsonArray commands;
        for (int i = 0; ScpiManager::m_scpiCommands[i].pattern != nullptr; ++i) {
            if (strlen(ScpiManager::m_scpiCommands[i].pattern) > 0) {
                commands.append(QString::fromLatin1(ScpiManager::m_scpiCommands[i].pattern));
            }
        }
        response["commands"] = commands;

        QByteArray jsonData = QJsonDocument(response).toJson();
        sendHttpResponse(client, jsonData, "application/json");
    };

    m_apiRoutes["/api/channels"] = [this](QTcpSocket* client) {
        QJsonObject response;
        response["channels"] = m_qmlbridge->getAllChannelsData();

        QByteArray jsonData = QJsonDocument(response).toJson();
        sendHttpResponse(client, jsonData, "application/json");
    };

    m_apiRoutes["/api/models"] = [this](QTcpSocket* client) {
        QJsonObject response = getModelsInfo();
        QByteArray jsonData = QJsonDocument(response).toJson();
        sendHttpResponse(client, jsonData, "application/json");
    };
}


WebServerManager::WebServerManager(QObject *parent) : QObject(parent)
{
    m_serverThread = new QThread(this);
    this->moveToThread(m_serverThread);

    connect(m_serverThread, &QThread::started, this, [this]() {
        m_httpServer = new QTcpServer(this);
        connect(m_httpServer, &QTcpServer::newConnection,this,[this](){
            QTcpSocket* client = m_httpServer->nextPendingConnection();
            if (m_clients.size() < 9) { // restrict connect number = 9
                client->setObjectName(QString("%1:%2").arg(client->peerAddress().toString()).arg(client->peerPort()));
                qCDebug(web_server) <<"[WebServerManager]:New HTTP client: "<< client->objectName();

                connect(client, &QTcpSocket::errorOccurred,this, [client](QAbstractSocket::SocketError error){
                    qCWarning(web_server)<<"[WebServerManager]:("<< client->objectName()<<")"<<error<<client->errorString();
                    }, Qt::DirectConnection);
                connect(client, &QTcpSocket::disconnected,this, [this, client](){
                    qCDebug(web_server)<<"[WebServerManager]: "<<client->objectName()<<" disconnected";
                    m_clients.removeOne(client);
                    client->deleteLater();
                    }, Qt::DirectConnection);
                connect(client, &QTcpSocket::readyRead,this, [this, client](){
                     m_readbuffer = client->readAll();
                    if (m_readbuffer.contains("\r\n\r\n")) {
                        QString requestLine = QString::fromUtf8(m_readbuffer).split("\r\n").first();
                        QStringList parts = requestLine.split(" ");

                        if (parts.size() >= 3) {
                            QString path = QUrl::fromPercentEncoding(parts[1].toUtf8());
                            qCDebug(web_server) <<"[handleHttpRequest]:HTTP request: "<< parts[0] << path;

                            if (m_apiRoutes.contains(path)) {
                                m_apiRoutes[path](client);
                                return;
                            }

                            if (m_staticFiles.contains(path)) {
                                QString resourcePath = m_staticFiles[path];
                                if (!m_fileCache.contains(path)) {
                                    QFile file(resourcePath);
                                    if (!file.open(QIODevice::ReadOnly)) {
                                        qCWarning(web_server)<<"[handleHttpRequest]: open web file: "<<resourcePath<<"failed!";
                                        sendHttpResponse(client, "500 Internal Server Error", "text/plain", 500);
                                        return;
                                    }

                                    m_fileCache[path] = file.readAll();
                                }

                                QString contentType = m_mimeTypes[QFileInfo(resourcePath).suffix()];
                                sendHttpResponse(client, m_fileCache[path], contentType);
                                return;
                            }

                            qCWarning(web_server)<<"[handleHttpRequest]: request route method not exist!";
                            sendHttpResponse(client, "404 Not Found", "text/plain", 404);
                            return;
                        }
                    }

                    sendHttpResponse(client, "Please access using a web browser.", "text/plain");
                    qCWarning(web_server)<<"[handleHttpRequest]: request format failed!";
                    }, Qt::DirectConnection);

                m_clients.append(client);
                return;
            }

            client->disconnectFromHost();
            client->deleteLater();
            },Qt::DirectConnection);

        if (m_httpServer->listen(QHostAddress::Any, Vxi11::HTTP_PORT)) {
            setupHTTPRoutes();

            m_wsServer = new QWebSocketServer("Leacesy",QWebSocketServer::NonSecureMode, this);
            connect(m_wsServer, &QWebSocketServer::newConnection,this, [this](){
                QWebSocket* socket = m_wsServer->nextPendingConnection();
                if (m_sockets.size() < 9) { // restrict connect number = 9
                    socket->setObjectName(QString("%1:%2").arg(socket->peerAddress().toString()).arg(socket->peerPort()));
                    qCDebug(web_server) <<"[WebServerManager]:New WebSocket client: "<< socket->objectName();

                    connect(socket,QOverload<QAbstractSocket::SocketError>::of(&QWebSocket::error),this, [socket](QAbstractSocket::SocketError error){
                        qCWarning(web_server)<<"[WebServerManager]:("<<socket->objectName()<<")"<< error <<socket->errorString();
                        }, Qt::DirectConnection);
                    connect(socket, &QWebSocket::disconnected,this, [this, socket](){
                        qCDebug(web_server)<<"[WebServerManager]: "<<socket->objectName()<<" disconnected";
                        m_sockets.removeOne(socket);
                        socket->deleteLater();
                        }, Qt::DirectConnection);
                    connect(socket, &QWebSocket::textMessageReceived,this, [this, socket](const QString &message){
                        qCDebug(web_server) <<"[onWsTextMessageReceived]:WEB request: "<<message;
                        QJsonDocument doc = QJsonDocument::fromJson(message.toUtf8());
                        if (!doc.isNull() && doc.isObject()) {
                            QJsonObject obj = doc.object();
                            QString type = obj["type"].toString();
                            if (m_webRoutes.contains(type)) {
                                switch (ConfigManager::s_remoteSt.load()) {
                                    case 0:emit isRemote(4);// fall through
                                    case 4:m_webRoutes[type](socket,obj);break;
                                    default:QJsonObject response;
                                            response["type"] = "scpi_response";
                                            response["result"] = "Other interfaces of the instrument are currently in operation";
                                            qCDebug(web_server)<<"[setupRoutes]:Currently in an alternative remote mode";
                                            socket->sendTextMessage(QJsonDocument(response).toJson());
                                }

                                return;
                            }

                            qCWarning(web_server)<<"[onWsTextMessageReceived]: request route method not exist!";
                        }}, Qt::DirectConnection);

                    m_sockets.append(socket);
                    return;
                }

                socket->disconnect();
                socket->deleteLater();
                },Qt::DirectConnection);

            if (m_wsServer->listen(QHostAddress::Any, Vxi11::WEB_PORT)) {
                setupWSRoutes();
                return;
            }

            qCCritical(web_server)<<"[startServer]: m_wsServer listen failed!";
            return;
        }

        qCCritical(web_server)<<"[startServer]: m_httpServer listen failed!";
    });

    m_serverThread->setObjectName("WebServer");
    m_serverThread->start();
}

WebServerManager::~WebServerManager()
{
    if (m_httpServer) {
        for (QTcpSocket *client : qAsConst(m_clients)) {
            client->disconnectFromHost();
            client->waitForDisconnected(600);
        }
        m_clients.clear();
        m_httpServer->close();
        delete m_httpServer;
        m_httpServer = nullptr;
    }

    if (m_wsServer) {
        for (QWebSocket* socket : qAsConst(m_sockets)) {
            socket->disconnect();
            socket->deleteLater();
        }
        m_sockets.clear();
        m_wsServer->close();
        delete m_wsServer;
        m_wsServer = nullptr;
    }

    if (m_serverThread) {
        m_serverThread->quit();
        m_serverThread->wait(1000); // wait 1s
        m_serverThread->deleteLater();
        delete m_serverThread;
        m_serverThread = nullptr;
    }

    qCDebug(web_server)<<"[~WebServerManager]:~WebServerManager Destroyed!!!";
}


bool WebServerManager::addModelFromNetwork(const QString &modelName, const QJsonArray &modelData) {
    if (!modelName.isEmpty() && !m_BatteryManager->m_models.contains(modelName)) {
        auto model = QSharedPointer<BatteryModel>::create();

        for (const auto &item : modelData) {
            if (!item.isNull() && item.isObject()) {
                QJsonObject pointObj = item.toObject();

                if (pointObj.contains("soc") && pointObj.contains("ocv") && pointObj.contains("imp")) {
                    BatteryDataPoint point;
                    point.soc = pointObj["soc"].toDouble();
                    point.ocv = pointObj["ocv"].toDouble();
                    point.imp = pointObj["imp"].toDouble();
                    model->data_points.append(point);
                }else{
                    qCWarning(web_server) << "[addModelFromNetwork]:Parameter lack error!";
                    return false;
                }
            }else{
                qCWarning(web_server) << "[addModelFromNetwork]:Parameter model format error!";
                return false;
            }
        }

        // model->name = modelName;   saveModel to set model->name
        m_BatteryManager->saveModel(model, modelName);
        return true;
    }

    qCWarning(web_server)<<"[addModelFromNetwork]:Parameter error or model incorrect!";
    return false;
}

QJsonObject  WebServerManager::getModelsInfo() const {
    QJsonObject result;
    QJsonArray modelsArray;

    for (auto it = m_BatteryManager->m_models.begin(); it != m_BatteryManager->m_models.end(); ++it) {
        QJsonObject modelInfo;
        modelInfo["name"] = it.key();

        QJsonArray dataArray;
        const auto &model = it.value();
        const auto &points = model->data_points;

        for (const auto &point : points) {
            QJsonObject pointObj;
            pointObj["soc"] = std::round(point.soc * 10.0) / 10.0;
            pointObj["ocv"] = std::round(point.ocv * 100.0) / 100.0;
            pointObj["esr"] = std::round(point.imp * 1000.0) / 1000.0;
            dataArray.append(pointObj);
        }

        modelInfo["data"] = dataArray;
        modelsArray.append(modelInfo);
    }

    result["models"] = modelsArray;
    result["status"] = "success";
    return result;
}

void WebServerManager::setupWSRoutes()
{
    m_webRoutes["scpi_command"] = [this](QWebSocket* socket, const QJsonObject& obj) {
        QByteArray cmd = (obj["command"].toString()+"\n").toUtf8();
        qCDebug(web_server)<<"[setupRoutes]:SCPI command received:" << cmd;
        QByteArray res = m_scpiManager->processCommand(cmd);

        if (!res.isEmpty()){
            QJsonObject response;
            response["type"] = "scpi_response";
            response["result"] = QString::fromUtf8(res);
            socket->sendTextMessage(QJsonDocument(response).toJson());
        }
    };

    m_webRoutes["channels_update"] = [this](QWebSocket* socket, const QJsonObject&) {
        QJsonObject channelData;
        channelData["type"] = "channels_response";
        channelData["channels"] = m_qmlbridge->getAllChannelsData();
        socket->sendTextMessage(QJsonDocument(channelData).toJson());
    };

    m_webRoutes["model_upload"] = [this](QWebSocket* socket, const QJsonObject& obj) {
        QJsonObject content = obj["content"].toObject();
        QString modelName = content["name"].toString();
        QJsonArray modelData = content["data"].toArray();

        QJsonObject response;
        if (addModelFromNetwork(modelName,modelData)) {
            m_qmlbridge->load_BatteryModel();
            response = getModelsInfo();
            response["type"] = "model_sync";
            socket->sendTextMessage(QJsonDocument(response).toJson());
        } else {
            response["type"] = "error";
            response["message"] = QString("Failed to save model \"%1\"").arg(modelName);
            socket->sendTextMessage(QJsonDocument(response).toJson());
        }
    };

    m_webRoutes["model_delete"] = [this](QWebSocket* socket, const QJsonObject& obj) {
        QJsonObject response;
        QString modelName = obj["name"].toString();

        if (m_BatteryManager->removeModel(modelName)) {
            m_qmlbridge->load_BatteryModel();
            response = getModelsInfo();
            response["type"] = "model_sync";
            socket->sendTextMessage(QJsonDocument(response).toJson());
        } else {
            response["type"] = "error";
            response["message"] = QString("Failed to delete model \"%1\"").arg(modelName);
            socket->sendTextMessage(QJsonDocument(response).toJson());
        }
    };
}
