[Logger]
logLevel=debug
#EnablelogFile=false

[Channel]
EnableUartMess=true
EnableCanMess=false

[Control]
EnableLANServer=true
EnableWEBServer=false
EnableCANServer=false
EnableUARTServer=false
EnableDisplay=false

[Device]
SerialNumber=SN-12306
Model=66004
GPIBID=5
CANID=6
