[Logger]
logLevel=info
#EnablelogFile=false

[Channel]
EnableUartMess=true
EnableCanMess=false

[Control]
EnableLANServer=true
EnableWEBServer=true
EnableCANServer=false
EnableUARTServer=false
EnableDisplay=true

[Device]
SerialNumber=SN-12306
Model=66004
GPIBID=5
CANID=6
